apiVersion: apps/v1
kind: Deployment
metadata:
  name: userinfo-service
spec:
  replicas: 2
  template:
    spec:
      containers:
        - name: userinfo-service
          image: userinfo-service-app-image
          