apiVersion: apps/v1
kind: Deployment
metadata:
  name: userinfo-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: userinfo
  template:
    metadata:
      labels:
        app: userinfo
    spec:
      containers:
        - name: userinfo-service
          image: nginx:alpine
          ports:
            - containerPort: 80