apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- ../../base
patches:
- path: patches/deployment.yaml
  target:
    kind: Deployment
    name: userinfo-service
- path: patches/configmap.yaml
  target:
    kind: ConfigMap
    name: userinfo-service-cm
images:
- name: userinfo-service-app-image
  newName: jovanie1795/userinfo-service
  newTag: 1781248178.5.1
