apiVersion: v1
kind: ConfigMap
metadata:
  name: userinfo-service
data:
  MANAGEMENT_METRICS_TAGS_APPLICATION: userinfo-service
  MANAGEMENT_ENDPOINT_METRICS_ENABLED: "true"
  MANAGEMENT_ENDPOINT_PROMETHEUS_ENABLED: "true"
  MANAGEMENT_ENDPOINTS_WEB_EXPOSURE_INCLUDE: health,prometheus,info
  MANAGEMENT_HEALTH_PROBES_ENABLED: "true"
  MANAGEMENT_ENDPOINT_HEALTH_PROBES_ENABLED: "true"
  MANAGEMENT_HEALTH_LIVENESSSTATE_ENABLED: "true"
  MANAGEMENT_HEALTH_READINESSSTATE_ENABLED: "true"
  MANAGEMENT_PROMETHEUS_METRICS_EXPORT_ENABLED: "true"
  MANAGEMENT_ENDPOINTS_JMX_EXPOSURE_INCLUDE: info
  MANAGEMENT_INFO_ENV_ENABLED: "true"
  MANAGEMENT_INFO_BUILD_ENABLED: "true"
  MANAGEMENT_INFO_JAVA_ENABLED: "true"
  MANAGEMENT_INFO_GIT_ENABLED: "true"
  MANAGEMENT_INFO_GIT_MODE: full