apiVersion: apps/v1
kind: Deployment
metadata:
  name: userinfo-service
  labels:
    app: userinfo-service
spec:
  selector:
    matchLabels:
      app: userinfo-service
  template:
    metadata:
      labels:
        app: userinfo-service
    spec:
      containers:
        - name: userinfo-service
          imagePullPolicy: Always
          ports:
            - name: http
              containerPort: 8080
              protocol: TCP
          
