apiVersion: v1
kind: Service
metadata:
  annotations:
    prometheus.io/path: /actuator/prometheus
    prometheus.io/port: '8080'
    prometheus.io/scrape: 'true'
  name: userinfo-service
  labels:
    app: userinfo-service
spec:
  ports:
    - name: http
      port: 8000
      protocol: TCP
      targetPort: http
  selector:
    app: userinfo-service
  type: ClusterIP
